modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
issueTrackerURL="${mod_issue_tracker}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="logo.png"
authors="${mod_author}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="curios"
mandatory=false
versionRange="${curios_version_range}"
referralUrl="https://github.com/TheIllusiveC4/Curios"
ordering="NONE"
side="BOTH"