# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
group=de.cech12.usefulhats
mod_version=6.10.2.0
mod_id=usefulhats
mod_name=Useful Hats
mod_author=Cech12
mod_license=The MIT License (MIT)
mod_url=https://github.com/cech12/UsefulHats
mod_issue_tracker=https://github.com/cech12/UsefulHats/issues
description=A mod which adds some useful hats.

# Common
java_version=21
minecraft_version=1.21.8
minecraft_version_range=[1.21.8, 1.22)

# Fabric
fabric_version=0.134.0+1.21.8
fabric_loader_version=0.17.3
cloth_config_version=19.0.147
mod_menu_version=15.0.0

# Forge
forge_version=58.1.0
forge_version_range=[58.1.0,)
forge_loader_version_range=[56,)

# NeoForge
neoforge_version=21.8.47
neoforge_version_range=[21.8.47,)
neoforge_loader_version_range=[2,)

# Trinkets
trinkets_version=3.11.0-1.21.6
cca_version=7.0.0-beta.1

# Accessories
accessories_version=1.3.8-beta+1.21.8
accessories_version_range=[1.3.8-beta,)

# Curios
curios_version=12.0.0+1.21.8
curios_version_range=[12.0.0,)

# Lucent
lucent_version=1.20.4-1.6.0
lucent_version_range=[1.6.0,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false