plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.accesstransformers'
    id 'net.minecraftforge.gradle'
}
jar {
    manifest {
        attributes["MixinConfigs"] = "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.10'
}

minecraft {
    // Automatically enable forge AccessTransformers if the file exists
    // This location is hardcoded in Forge and can not be changed.
    // https://github.com/MinecraftForge/MinecraftForge/blob/be1698bb1554f9c8fa2f58e32b9ab70bc4385e60/fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java#L123
    // Forge still uses SRG names during compile time, so we cannot use the common AT's
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = true
    }

    runs {
        configureEach {
            args "-mixin.config=${mod_id}.mixins.json"
            args "-mixin.config=${mod_id}.forge.mixins.json"
        }
        client {
            workingDir = file('runs/client')
        }
        server {
            workingDir = file('runs/server')
        }
        data {
            workingDir = file('runs/data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

//duplicate accesstransformer
tasks.withType(Copy).configureEach {
    if (name == 'processResources' || name.endsWith('ProcessResources')) {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
}
tasks.withType(Jar).configureEach {
    if (name == 'sourcesJar' || name.endsWith('SourcesJar')) {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
}

test {
    failOnNoDiscoveredTests = false
}

sourceSets.main.resources.srcDir 'src/generated/resources'

publishing {
    publications {
        mavenJava(MavenPublication) {
        }
    }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}