modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="${mod_issue_tracker}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="logo.png"
authors="${mod_author}"
description='''${mod_description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="accessories"
type="optional"
versionRange="${accessories_version_range}"
referralUrl="https://github.com/wisp-forest/accessories/"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="curios"
type="optional"
versionRange="${curios_continuation_version_range}"
referralUrl="https://github.com/SSKirillSS/Curios"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="baubles"
type="optional"
versionRange="${baubles2_version_range}"
referralUrl="https://github.com/Tanticle/baubles"
ordering="NONE"
side="BOTH"