plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

repositories {
    //for Accessories
    maven { url = "https://maven.wispforest.io/releases" }
    maven { url = "https://maven.su5ed.dev/releases" }
    maven { url = "https://maven.fabricmc.net/" }
    maven { url = "https://maven.shedaniel.me/" }
    maven { url = "https://maven.blamejared.com/" }
    //for Lucent
    exclusiveContent {
        forRepository {
            maven {
                name = "Modding Legacy Maven"
                url = "https://maven.moddinglegacy.com/artifactory/modding-legacy/"
            }
        }
        filter {
            includeGroup "com.legacy"
        }
    }
}

dependencies {
    //compileOnly("io.wispforest:accessories-neoforge:${accessories_version}")
    //runtimeOnly("io.wispforest:accessories-neoforge:${accessories_version}")

    //compileOnly("com.legacy:lucent:${project.lucent_version}")
    //runtimeOnly("com.legacy:lucent:${project.lucent_version}")
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            clientData()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}