# This workflow builds the project on each push and pull request and publish it on new tags

name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
    tags: ["1.16*"]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Build
    uses: cech12/MinecraftModActions/.github/workflows/build.yml@main
    with:
      java-version: 8
  codeql:
    needs: build
    name: CodeQL
    uses: cech12/MinecraftModActions/.github/workflows/codeql-analysis.yml@main
    with:
      java-version: 8
  publish-github:
    needs: codeql
    if: startsWith(github.ref, 'refs/tags/')
    name: Publish Github
    uses: cech12/MinecraftModActions/.github/workflows/publish-github.yml@main
    with:
      java-version: 8
      mod-name: Useful Hats
      mod-id: usefulhats
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  publish-curseforge:
    needs: publish-github
    if: startsWith(github.ref, 'refs/tags/')
    name: Publish Curseforge
    uses: cech12/MinecraftModActions/.github/workflows/publish-curseforge.yml@main
    with:
      java-version: 8
    secrets:
      curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}
