name: Issue or PR to project
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add item to project
        uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/users/cech12/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}